### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by fredrikw** [rschiang/unity-dark-ui#10]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:55:11)
Object.checkFullscreen (/Users/fwr/.atom/packages/unity-dark-ui/lib/unity-ui.coffee:29:11)
```

**Comment by rschiang** [comment]
Updated from upstream. Problem should be solved now. :)
